import io, re, os

PROJECT_DIR = r'c:\Users\hp zbook\Desktop\AI-Agent-Pro-main'

# 1. Safely remove unused images
for f in ['error_screen.png', 'icon-512.png', 'og-image.png', 'favicon.svg']:
    p = os.path.join(PROJECT_DIR, f)
    if os.path.exists(p):
        os.remove(p)

# 2. Update index.html
html_path = os.path.join(PROJECT_DIR, 'index.html')
with io.open(html_path, 'r', encoding='utf-8') as f:
    html = f.read()

html = html.replace('https://ai-agent-pro.pages.dev/og-image.png', 'ai_avatar.png')
html = html.replace('https://aiagentpro.com/og-image.png', 'ai_avatar.png')
html = html.replace('icon-512.png', 'ai_avatar.png')
html = html.replace('favicon.svg', 'ai_avatar.png')

with io.open(html_path, 'w', encoding='utf-8') as f:
    f.write(html)

# 3. Update login.html
login_path = os.path.join(PROJECT_DIR, 'login.html')
with io.open(login_path, 'r', encoding='utf-8') as f:
    login = f.read()

login = login.replace('<link rel="icon" type="image/svg+xml" href="favicon.svg">', '<link rel="icon" type="image/png" href="ai_avatar.png">')
login = login.replace('<link rel="apple-touch-icon" href="icon-512.png">', '<link rel="apple-touch-icon" href="ai_avatar.png">')
login = login.replace('icon-512.png', 'ai_avatar.png')
login = login.replace('og-image.png', 'ai_avatar.png')

with io.open(login_path, 'w', encoding='utf-8') as f:
    f.write(login)

# 4. Remove 'generated by AI' or 'AI-generated' from README if exists
readme_path = os.path.join(PROJECT_DIR, 'README.md')
if os.path.exists(readme_path):
    with io.open(readme_path, 'r', encoding='utf-8') as f:
        readme = f.read()
    readme = re.sub(r'(?i).*built by ai.*\n', '', readme)
    readme = re.sub(r'(?i).*generated by.*\n', '', readme)
    with io.open(readme_path, 'w', encoding='utf-8') as f:
        f.write(readme)
        
print("Images unified to ai_avatar.png, safe cleanup done.")
